services:
  db:
    image: postgres
    restart: always
    # ports:
    #   - '${DB_PORT}:${DB_PORT}'
    environment:
      # POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PASSWORD: example
      # POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}

  redis:
    image: redis
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    restart: always
